<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>后台管理-权限管理</title>
        <?php $this->render('include/headersource', true); ?>
        <!-- 此处引入资源文件或自定义样式及脚本 -->
        <style>
            #list.table th, #list.table td, #search th, #search td { 
                text-align: center;
                vertical-align: middle; 
            }
        </style>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php $this->render('include/header', true); ?>
            <?php $this->render('include/leftbar', true); ?>
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>权限管理<small>List</small></h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">
                            <i class="fa fa-dashboard"></i>
                                后台管理
                            </a>
                        </li>
                        <li class="active">
                            权限列表
                        </li>
                    </ol>
                </section>
                <section class="content">
                <!-- 此处是主内容区域 Start -->
                <!-- search -->
                <div class="row">
                <div class="col-md-12">
                <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Search</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body table-responsive" style="display: block;">
                <form id="searchform" method="get" action="/AdmAuth/list">
                <table id="search" class="table">
                    <tr>
                        <td width="150px">权限名称：</td>
                        <td width="150px"><input type="text" name="name" value="<?php echo $this->name; ?>" class="form-control" placeholder="权限名称"></td>
                        <td><input type="submit" class="btn btn-default" value="查询"></td>
                    </tr>
                </table>
                </form>
                </div>
                </div>
                </div>
                </div>
                <!-- list -->
                <div class="row">
                <div class="col-xs-12">
                <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Table List</h3>
                    <div class="pull-right">
                        <span class="glyphicon glyphicon-th-list"></span>
                        <a class="glyphicon glyphicon-plus" href="/AdmAuth/index"></a>
                    </div>
                </div>
                <div class="box-body table-responsive">
                <form action="/AdmUser/deleteuserauth" method="post">
                <table id="list" class="table table-bordered table-condensed table-striped table-hover">
                <tbody>
                    <tr>
                        <th width="10px">#</th>
                        <th>权限名称</th>
                        <th>创建时间</th>
                        <th>权限持有者</th>
                    </tr>
                    <?php foreach ($this->list['records'] as $v) {
                    echo '<tr>';
                        echo '<td >'.$v['id'].'</td>';
                        echo '<td  nowrap>'.$v['name'].'</td>';
                        echo '<td nowrap>'.$v['ctime'].'</td>';
                        echo '<td>';
                        $users = \App\Models\Svc\AdmUserSvc::getUidByAuth($v['id']);
                        foreach ($users as $user) {
                            echo '<span style="width:120px;float:left;"><input name="id_auth[]" type="checkbox" value="'.$v['id'].'_'.$user['uid'].'"> '.$user['user']."</span>";
                        }
                        echo '</td>';
                    echo '</tr>';
                    } ?>
                </tbody>
                </table>
                <input type="submit" class="btn btn-default" value="为选中的人移除对应权限">
                </form>
                </div>
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <?php $this->render('include/pager', true); ?>
                    </ul>
                </div>
                </div>
                </div>
                </div>
                <!-- 此处是主内容区域 End -->
                </section>
            </div>
            <?php $this->render('include/footer', true); ?>
            <?php $this->render('include/rightbar', true); ?>
        </div>
        <?php $this->render('include/footersource', true); ?>
        <!-- JavaScript引用和代码请集中写入此处 Start -->
        <!-- JavaScript引用和代码请集中写入此处 End -->
    </body>
</html>