#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

foreach ($argv as $v) {
    if (strpos($v, '--env') !== false) {
        putenv('ENV_LUMEN_ENV='.str_replace('--env=', '', $v));
        break;
    }
}
if (!file_exists(__DIR__.'/config/env_'.getenv('ENV_LUMEN_ENV'))) {
    echo 'env file not exists!!'."\r\n";exit;
}
$app = require __DIR__.'/bootstrap/app.php';
\App\Support\Loader::init();

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
