<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>后台管理-菜单管理</title>
        <?php $this->render('include/headersource', true); ?>
        <!-- 此处引入资源文件或自定义样式及脚本 -->
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php $this->render('include/header', true); ?>
            <?php $this->render('include/leftbar', true); ?>
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>菜单管理<small>Edit</small></h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">
                            <i class="fa fa-dashboard"></i>
                                后台管理
                            </a>
                        </li>
                        <li class="active">
                            菜单管理
                        </li>
                    </ol>
                </section>
                <section class="content">
                <!-- 此处是主内容区域 Start -->
                <div class="row">
                <div class="col-md-12">
                <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="pull-right">
                        <?php if ($this->data->id): ?>
                        <span class="glyphicon glyphicon-edit"></span>
                        <a class="glyphicon glyphicon-plus" href="/AdmMenu/index/"></a>
                        <a class="glyphicon glyphicon-th-list" href="/AdmMenu/list/"></a>
                        <?php else: ?>
                        <span class="glyphicon glyphicon-plus"></span>
                        <a class="glyphicon glyphicon-th-list" href="/AdmMenu/list/"></a>
                        <?php endif ?>
                    </div>
                </div>
                <?php $data = $this->data; ?>
                <form class="form-horizontal" method="post" action="/AdmMenu/modify/?id=<?php echo $data->id;?>" name="myform" id="myform">
                    <div class="box-body table-responsive">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">一级菜单：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="oneclass" value="<?php echo $data->oneclass; ?>" placeholder="一级菜单">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">二级菜单：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="name" value="<?php echo $data->name; ?>" placeholder="二级菜单">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">菜单URL</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="url" value="<?php echo $data->url; ?>" placeholder="菜单URL">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权限：</label>
                            <div class="col-sm-10">
                                <select class="form-control" style="width:200px;"  name="aid">
                                <option value="">请选择</option>
                                <?php foreach ($this->auths as $k => $v): ?>
                                    <?php if ($v['id'] == $data->aid) {
                                        echo '<option value="'.$v['id'].'" selected>'.$v['id'].'-'.$v['name'].'</option>';
                                    } else {
                                        echo '<option value="'.$v['id'].'">'.$v['id'].'-'.$v['name'].'</option>';
                                    } ?>
                                <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">排序：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="sort" value="<?php echo $data->sort; ?>" placeholder="排序">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">curr_menu：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="curr_menu" value="<?php echo $data->curr_menu; ?>" placeholder="curr_menu">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">curr_submenu：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="curr_submenu" value="<?php echo $data->curr_submenu; ?>" placeholder="curr_submenu">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Icon：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="icon" value="<?php echo $data->icon; ?>" placeholder="Icon">
                                <p class="help-block">图标针对一级菜单，当此菜单作为第一个子菜单时生效：<a href="http://ddj.siteadm.yuandalu.com/static/admin-lte/pages/UI/icons.html" target="_blan">&nbsp;&nbsp;Icon list fa-xxx</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" id="myButton" data-loading-text="Loading..." class="btn btn-primary">提交修改</button>
                    </div>
                </form>
                </div>
                </div>
                </div>
                <!-- 此处是主内容区域 End -->
                </section>
            </div>
            <?php $this->render('include/footer', true); ?>
            <?php $this->render('include/rightbar', true); ?>
        </div>
        <?php $this->render('include/footersource', true); ?>
        <!-- JavaScript引用和代码请集中写入此处 Start -->
        <!-- JavaScript引用和代码请集中写入此处 End -->
    </body>
</html>