<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>后台管理-菜单管理</title>
        <?php $this->render('include/headersource', true); ?>
        <!-- 此处引入资源文件或自定义样式及脚本 -->
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php $this->render('include/header', true); ?>
            <?php $this->render('include/leftbar', true); ?>
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>菜单管理<small>Add</small></h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">
                            <i class="fa fa-dashboard"></i>
                                后台管理
                            </a>
                        </li>
                        <li class="active">
                            菜单管理
                        </li>
                    </ol>
                </section>
                <section class="content">
                <!-- 此处是主内容区域 Start -->
                <div class="row">
                <div class="col-md-12">
                <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="pull-right">
                        <span class="glyphicon glyphicon-plus"></span>
                        <a class="glyphicon glyphicon-th-list" href="/AdmMenu/list/"></a>
                    </div>
                </div>
                <?php $data = $this->data; ?>
                <form class="form-horizontal" method="post" action="/AdmMenu/add/" name="myform" id="myform">
                    <div class="box-body table-responsive">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">一级菜单：</label>
                            <div class="col-sm-10">
                                <span id="onclass">
                                <select class="form-control" style="width:200px;"  name="groupid" id="groupid">
                                <option value="">请选择</option>
                                <?php foreach ($this->oneclass as $k => $v): ?>
                                    <?php echo "<option value='$v[groupid],$v[oneclass]'>",$v['oneclass'],"</option>"; ?>
                                <?php endforeach ?>
                                </select>
                                &nbsp;&nbsp;<a href="javascript::" onclick="add()">+新增</a></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">二级菜单</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="name" placeholder="二级菜单">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">菜单URL：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="url" placeholder="菜单URL">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权限：</label>
                            <div class="col-sm-10">
                                <select class="form-control" style="width:200px;"  name="aid">
                                <option value="">请选择</option>
                                <?php foreach ($this->auths as $k => $v): ?>
                                    <?php echo '<option value="'.$v['id'].'">'.$v['id'].'-'.$v['name'].'</option>'; ?>
                                <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">排序：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="sort" placeholder="排序">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">curr_menu：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="curr_menu" placeholder="curr_menu">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">curr_submenu：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" name="curr_submenu" placeholder="curr_submenu">
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary" onclick="return submitForm()">提交</button>
                    </div>
                </form>
                </div>
                </div>
                </div>
                <!-- 此处是主内容区域 End -->
                </section>
            </div>
            <?php $this->render('include/footer', true); ?>
            <?php $this->render('include/rightbar', true); ?>
        </div>
        <?php $this->render('include/footersource', true); ?>
        <!-- JavaScript引用和代码请集中写入此处 Start -->
        <script src="/static/js/msg_util.js"></script>
        <script type="text/javascript">
            function submitForm()
            {
                $.ajax({
                    type:"GET",
                    data:$("#myform").serialize(),
                    url:"/AdmMenu/add/",
                    dataType:"html",
                    cache: false,
                    success:function(data){
                        MsgUtil.show(data);
                    }
                });
                return false;
            }

            function add()
            {
                var str = '<input class="text-input small-input" type="text" name="oneclass" id="oneclass" value="" >&nbsp;&nbsp;<a href="javascript::" onclick="cancle()">+取消</a>';
                $("#onclass").html(str);
            }
            function cancle()
            {
                window.location.href=window.location.href;
            }
        </script>
        <!-- JavaScript引用和代码请集中写入此处 End -->
    </body>
</html>