<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>后台管理-菜单管理</title>
        <?php $this->render('include/headersource', true); ?>
        <!-- 此处引入资源文件或自定义样式及脚本 -->
        <style>
            #list.table th, #list.table td, #search th, #search td { 
                text-align: center;
                vertical-align: middle; 
            }
        </style>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php $this->render('include/header', true); ?>
            <?php $this->render('include/leftbar', true); ?>
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>菜单管理<small>List</small></h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">
                            <i class="fa fa-dashboard"></i>
                                后台管理
                            </a>
                        </li>
                        <li class="active">
                            菜单管理列表
                        </li>
                    </ol>
                </section>
                <section class="content">
                <!-- 此处是主内容区域 Start -->
                <!-- search -->
                <div class="row">
                <div class="col-md-12">
                <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Search</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body table-responsive" style="display: block;">
                <form id="searchform" method="post" action="/AdmMenu/list">
                <table id="search" class="table">
                    <tr>
                        <td width="80px">ID：</td>
                        <td width="150px"><input type="text" name="id" value="<?php echo $this->id; ?>" class="form-control" placeholder="ID"></td>
                        <td width="80px">一级名称：</td>
                        <td width="150px"><input type="text" name="oneclass" value="<?php echo $this->oneclass; ?>" class="form-control" placeholder="一级名称"></td>
                        <td width="80px">二级名称：</td>
                        <td width="150px"><input type="text" name="name" value="<?php echo $this->name; ?>" class="form-control" placeholder="二级名称"></td>
                        <td width="80px"><input type="submit" class="btn btn-default" value="查询"></td>
                    </tr>
                </table>
                </form>
                </div>
                </div>
                </div>
                </div>
                <!-- list -->
                <div class="row">
                <div class="col-xs-12">
                <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Table List</h3>
                    <div class="pull-right">
                        <span class="glyphicon glyphicon-th-list"></span>
                        <a class="glyphicon glyphicon-plus" href="/AdmMenu/index"></a>
                    </div>
                </div>
                <div class="box-body table-responsive">
                <table id="list" class="table table-bordered table-condensed table-striped table-hover">
                <tbody>
                    <tr>
                        <th width="10px">#</th>
                        <th > 一级目录 </th>
                        <th > 二级目录 </th>
                        <th > 地址 </th>
                        <th > 排序 </th>
                        <th > 组id </th>
                        <th > 权限id </th>
                        <th > curr_menu </th>
                        <th > curr_submenu </th>
                        <th > 操作 </th>
                    </tr>
                    <?php foreach ($this->list['records'] as $v) {
                    echo "<tr>";
                        echo '<td >'.$v['id'].'</td>';
                        echo '<td >'.$v['oneclass'].'</td>';
                        echo '<td >'.$v['name'].'</td>';
                        echo '<td >'.$v['url'].'</td>';
                        echo '<td >'.$v['sort'].'</td>';
                        echo '<td >'.$v['groupid'].'</td>';
                        echo '<td >'.$v['aid'].'</td>';
                        echo '<td >'.$v['curr_menu'].'</td>';
                        echo '<td >'.$v['curr_submenu'].'</td>';
                        echo '<td ><a class="glyphicon glyphicon-edit" title="编辑" href="/AdmMenu/edit/?id='.$v[id].'"></a></td>';
                    echo '</tr>';
                    } ?>
                </tbody>
                </table>
                </div>
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <?php $this->render('include/pager', true); ?>
                    </ul>
                </div>
                </div>
                </div>
                </div>
                <!-- 此处是主内容区域 End -->
                </section>
            </div>
            <?php $this->render('include/footer', true); ?>
            <?php $this->render('include/rightbar', true); ?>
        </div>
        <?php $this->render('include/footersource', true); ?>
        <!-- JavaScript引用和代码请集中写入此处 Start -->
        <!-- JavaScript引用和代码请集中写入此处 End -->
    </body>
</html>
