<!DOCTYPE html>
<html>
<head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
<meta http-equiv="refresh" content="3;url=/">
<title><?php echo $this->err_msg; ?></title>
<style>
    body{
        min-height:100%;
        background:#76b5f2;
        text-align:center;
    }
</style>
</head>
<body>
<a href='/'><img src="/" alt="<?php echo $this->err_msg; ?>" width="1000"></a>
</body>
</html>