<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>后台管理-菜单管理</title>
        <?php $this->render('include/headersource', true); ?>
        <!-- 此处引入资源文件或自定义样式及脚本 -->
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php $this->render('include/header', true); ?>
            <?php $this->render('include/leftbar', true); ?>
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>菜单管理<small>Edit</small></h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">
                            <i class="fa fa-dashboard"></i>
                                后台管理
                            </a>
                        </li>
                        <li class="active">
                            菜单管理
                        </li>
                    </ol>
                </section>
                <section class="content">
                <!-- 此处是主内容区域 Start -->
                <div class="row">
                <div class="col-md-12">
                <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="pull-right">
                        <span class="glyphicon glyphicon-edit"></span>
                        <a class="glyphicon glyphicon-plus" href="/AdmAuthNode/index/"></a>
                        <a class="glyphicon glyphicon-th-list" href="/AdmAuthNode/list/"></a>
                    </div>
                </div>
                <?php $data = $this->data; ?>
                <form class="form-horizontal" method="post" action="/AdmAuthNode/modify/?id=<?php echo $data->id;?>" name="myform" id="myform">
                    <div class="box-body table-responsive">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权限名称：</label>
                            <div class="col-sm-10">
                                <select class="form-control" style="width:200px;"  name="aid">
                                <option value="0">请选择权限</option>
                                <?php foreach ($this->auths as $k => $v): ?>
                                    <?php if ($v['id'] == $data->aid) {
                                        echo '<option value="'.$v['id'].'" selected>'.$v['id'].'-'.$v['name'].'</option>';
                                    } else {
                                        echo '<option value="'.$v['id'].'">'.$v['id'].'-'.$v['name'].'</option>';
                                    } ?>
                                <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">contr：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" value="<?php echo $data->contr;?>" name="contr" placeholder="contr">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">action：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" style="width:200px;" value="<?php echo $data->action;?>" name="action" placeholder="action">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">验证模式：</label>
                            <div class="col-sm-10">
                                <select class="form-control" style="width:200px;"  name="verify">
                                <?php foreach (\App\Models\Entity\AdmAuthNode::$VERIFY as $k => $v): ?>
                                    <?php if ($k == $data->verify) {
                                        echo '<option value="'.$k.'" selected>'.$k.'-'.$v['name'].'</option>';
                                    } else {
                                        echo '<option value="'.$k.'">'.$k.'-'.$v['name'].'</option>';
                                    } ?>
                                <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">提交修改</button>
                    </div>
                </form>
                </div>
                </div>
                </div>
                <!-- 此处是主内容区域 End -->
                </section>
            </div>
            <?php $this->render('include/footer', true); ?>
            <?php $this->render('include/rightbar', true); ?>
        </div>
        <?php $this->render('include/footersource', true); ?>
        <!-- JavaScript引用和代码请集中写入此处 Start -->
        <!-- JavaScript引用和代码请集中写入此处 End -->
    </body>
</html>