<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

		<title>贵学教育管理系统</title>

		<!--                       CSS                       -->

		<!-- Reset Stylesheet -->
		<link rel="stylesheet" href="/static/admin/css/reset.css" type="text/css" media="screen" />

		<!-- Main Stylesheet -->

		<link rel="stylesheet" href="/static/admin/css/style.css" type="text/css" media="screen" />

		<!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
		<link rel="stylesheet" href="/static/admin/css/invalid.css" type="text/css" media="screen" />

		<!-- Colour Schemes

		Default colour scheme is green. Uncomment prefered stylesheet to use it.

		<link rel="stylesheet" href="/static/admin/css/blue.css" type="text/css" media="screen" />

		<link rel="stylesheet" href="/static/admin/css/red.css" type="text/css" media="screen" />

		-->

		<!-- Internet Explorer Fixes Stylesheet -->

		<!--[if lte IE 7]>
			<link rel="stylesheet" href="/static/admin/css/ie.css" type="text/css" media="screen" />
		<![endif]-->

		<!--                       Javascripts                       -->

		<!-- jQuery -->
		<script type="text/javascript" src="/static/admin-lte/plugins/jQuery/jQuery-2.1.4.min.js"></script>


		<!-- jQuery Configuration -->
		<script type="text/javascript" src="/static/admin/scripts/simpla.jquery.configuration.js"></script>

		<!-- Facebox jQuery Plugin -->
		<script type="text/javascript" src="/static/admin/scripts/facebox.js"></script>
		<!-- jQuery WYSIWYG Plugin -->



		<script type="text/javascript" src="/static/js/captcha.js"></script>

	</head>

	<body id="login">

		<div id="login-wrapper" class="png_bg">
			<div id="login-top">

				<h1>贵学教育管理系统</h1>
				<!-- Logo (221px width) -->
			</div> <!-- End #logn-top -->

			<div id="login-content">
			<br/><br/>
				<form action="/index/login/" method="post" >

					<div class="notification information png_bg">
						<div>
							请使用邮箱名与企业邮箱密码登录
						</div>
					</div>

					<p>

						<label>用户名: </label>
						<input name="user" class="text-input">
					</p>
					<div class="clear"></div>
					<p>
						<label>密　码: </label>
						<input class="text-input" type="password"  name="pwd"/>

					</p>
                    <div class="clear"></div>
					<p>
                    <table>
					<tr>
						<td>
							<label>验证码：</label>
						</td>
						<td>
							<input type="hidden" name="ip" id="ip" value="">
							<input class="text-input" name="security_code" size=4 style="width:60px;margin-bottom:0px;margin-right:10px;margin-left:15px;">
						</td>
						<td>
							<a href="JavaScript: newCaptcha();"><div style="clear:both;width:80px;height:30px;" id="captcha" border="0" /></a>
						</td>
					</tr>
					</table>

					</p>



					<div class="clear"></div>
					<p>
						<input type="hidden" name="go" value="<?php echo $this->go; ?>" />
						<input class="button" type="submit" value="登&nbsp;&nbsp;录"  style="width:auto"/>
					</p>

				</form>

			</div> <!-- End #login-content -->

		</div> <!-- End #login-wrapper -->

  </body>
  </html>

                <div id="main">
				<?php if($this->logined){?>
					<h3>欢迎您 <?php echo $this->user;?>，您具有的权限如下：</h3>
					<ul class="authlist">
					<?php
						foreach( $this->auth as $v)
						{
							echo "<li>",Auth::$authname[$v],"</li>";
						}
					?>
					</ul>
				<?php }else{?>

				<?php }?>
                </div>
                <!-- // #main -->
<script type="text/javascript">
function newCaptcha()
{/*{{{*/
	captchaUtil.create('captcha');
}/*}}}*/
newCaptcha();
</script>
