<!-- REQUIRED JS SCRIPTS -->
<!-- jQuery 2.1.4 -->
<script src="/static/admin-lte/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="/static/admin-lte/bootstrap/js/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/admin-lte/dist/js/app.min.js"></script>
<!-- jquery-confirm -->
<script src="/static/plugins/jquery-confirm/dist/jquery-confirm.min.js"></script>
<!-- Optionally, you can add Slimscroll and FastClick plugins. Both of
these plugins are recommended to enhance the user experience. Slimscroll
is required when using the fixed layout.