<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.5 -->
<link rel="stylesheet" href="/static/admin-lte/bootstrap/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="/static/plugins/ionicons/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="/static/admin-lte/dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="/static/admin-lte/dist/css/skins/skin-blue.min.css">
<!-- jquery-confirm -->
<link rel="stylesheet" href="/static/plugins/jquery-confirm/dist/jquery-confirm.min.css">
<style>
/*弹出框被后台样式覆盖了一个最小值导致样式有问题，在这里做一个还原*/
.content {
    min-height: 40px;
}
</style>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file://
-->
<!--[if lt IE 9]>
    <script src="/static/admin-lte/cache/html5shiv.min.js"></script>
    <script src="/static/admin-lte/cache/respond.min.js"></script>
<![endif]-->
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->