<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/static/images/logo.jpg" class="img-circle" alt="LOGO">
            </div>
            <div class="pull-left info">
                <p>
                    <?php echo $this->adminUserObj->name;?>
                </p>
                <!-- 身份 -->
                <a><i class="fa fa-circle text-success"></i>
                    <?php echo $this->adminUserObj->role;?>
                </a>
            </div>
        </div>
        <!-- search form (Optional) -->
<!--         <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search">
                        </i>
                    </button>
                </span>
            </div>
        </form> -->
        <!-- /.search form -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">
                Menu
            </li>
            <li class="<?php echo empty($this->curr_menu)?'active':''; ?>">
                <a href="/Index"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
            </li>
<?php
$curUid = $this->adminUserObj->id;
$haveauth = \App\Models\Svc\AdmAuthSvc::getAuthByUid($curUid);// 已经有的权限
$menuList = \App\Models\Svc\AdmMenuSvc::getMenus();
$tempArr = array();
$curr_submenus = array();

foreach ($menuList as $v) {
    // 由于之前的表结构所设定，所以如果强制验证某个节点之后要排除他对应的菜单，请在数组加入排除的权限ID，最好节点单独建立一个权限
    if (in_array($v['aid'], array('11')) && !in_array($v['aid'], $haveauth)) {
        continue;
    } elseif (!$this->adminUserObj->isSuper() && (!$v['aid'] || !in_array($v['aid'], $haveauth))) {
        continue;
    }
    $tempArr[$v['oneclass']][] = $v;
}
foreach ($tempArr as $k => $v) {
    foreach ($v as $vv) {
        $curr_submenus[$k][] = $vv['curr_submenu'];
    }
}
?>
            <?php foreach ($tempArr as $key => $value): ?>
            <li class="treeview<?php if($this->curr_menu==$value[0]['curr_menu'] && in_array($this->curr_submenu, $curr_submenus[$key])){echo ' active';}?>">
                <a href="#">
                    <i class="fa <?php echo $value[0]['icon']; ?>"></i>
                    <span><?php echo $key; ?></span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu"<?php if($this->curr_menu==$value[0]['curr_menu']){echo ' active';}?>>
                    <?php foreach ($value as $v): ?>
                    <li<?php if($this->curr_submenu==$v['curr_submenu']){echo ' class="active"';}?>>
                        <a href="<?php echo $v['url']; ?>">
                        <i class="fa fa-circle-o text-aqua"></i>
                            <?php echo $v['name'] ;?>
                        </a>
                    </li>
                    <?php endforeach ?>
                </ul>
            </li>
            <?php endforeach ?>
            <!-- Optionally, you can add icons to the links -->
            <!-- <li class="active">
                <a href="#">
                    <i class="fa fa-link">
                    </i>
                    <span>
                        Link
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-link">
                    </i>
                    <span>
                        Another Link
                    </span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-link">
                    </i>
                    <span>
                        Multilevel
                    </span>
                    <i class="fa fa-angle-left pull-right">
                    </i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="#">
                            Link in level 2
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Link in level 2
                        </a>
                    </li>
                </ul>
            </li> -->
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>