<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>后台管理-用户权限列表</title>
        <?php $this->render('include/headersource', true); ?>
        <!-- 此处引入资源文件或自定义样式及脚本 -->
        <style>
            #list.table th, #list.table td, #search th, #search td { 
                text-align: center;
                vertical-align: middle; 
            }
        </style>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php $this->render('include/header', true); ?>
            <?php $this->render('include/leftbar', true); ?>
            <div class="content-wrapper">
                <section class="content-header">
                    <h1>用户权限列表<small>List</small></h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">
                            <i class="fa fa-dashboard"></i>
                                后台管理
                            </a>
                        </li>
                        <li class="active">
                            用户权限列表
                        </li>
                    </ol>
                </section>
                <section class="content">
                <!-- 此处是主内容区域 Start -->
                <!-- list -->
                <div class="row">
                <div class="col-xs-12">
                <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Table List</h3>
                    <div class="pull-right">
                        <a class="glyphicon glyphicon-th-list" href="/AdmUser/index"></a>
                    </div>
                </div>
                <div class="box-body table-responsive">
                <table id="list" class="table table-bordered table-condensed table-striped table-hover">
                <tbody>
                    <tr>
                        <th><h4>ID</h4></th>
                        <th><h4>权限拥有人</h4></th>
                        <th><h4>权限</h4></th>
                        <th><h4>系统角色</h4></th>
                        <th><h4>操作</h4></th>
                    </tr>
                    <?php foreach ($this->data as $v) {
                    echo "<tr id=\"m_".$v['aid']."\">";
                        echo "<td>".($key+1)."</td>";
                        echo "<td>".$this->admin[0]['name']."</td>";
                        echo "<td>".$v['name']."</td>";
                        echo "<td>".$this->admin[0]['role']."</td>";
                        echo "<td><a class='fa fa-trash-o' title='删除权限' href='javascript:void(0)' onclick='forbidden(".$v['aid'].",".$v['uid'].")'></a>&nbsp;</td>";
                    echo "</tr>";
                    } ?>
                </tbody>
                </table>
                </div>
                <div class="box-footer clearfix">
                </div>
                </div>
                </div>
                </div>
                <!-- 此处是主内容区域 End -->
                </section>
            </div>
            <?php $this->render('include/footer', true); ?>
            <?php $this->render('include/rightbar', true); ?>
        </div>
        <?php $this->render('include/footersource', true); ?>
        <!-- JavaScript引用和代码请集中写入此处 Start -->
        <script type="text/javascript">
        function forbidden(aid, uid)
        {
            $.confirm({
                title: '警告!',
                content: '是否删除此项权限？',
                confirm: function() {
                    $.ajax({
                        type: "POST",
                        url: "/AdmUser/delauth/",
                        data: {'id':aid,'uid':uid},
                        dataType:"json",
                        cache: false,
                        success: function(data){
                            if (data.code == "succ") {
                                $("#m_"+aid).remove();
                            }
                        }
                    });
                }
            });
        }
        </script>
        <!-- JavaScript引用和代码请集中写入此处 End -->
    </body>
</html>